- src: git+ssh://git@github.com/zcapitalz/devops-labs-ansible-role-install-docker.git
  version: "4abe8d2d1b6784e9a6ced7f9235ab71a219fb409"
  name: install-docker
  
- src: git+ssh://git@github.com/zcapitalz/devops-labs-ansible-role-nginx.git
  version: "58da57dee6521267bcdd2d002c5596180c89caa0"
  name: nginx